#!/usr/bin/env python3
#
#     platforms.illumina.data.py: handle Illumina sequencer runs
#     Copyright (C) University of Manchester 2011-2025 Peter Briggs
#
########################################################################
#
# platforms.illumina.data.py
#
#########################################################################

"""
Provides classes for extracting data about Illumina sequencing runs
and derived data, by examining directory structures, data files and
naming conventions.

The main classes are:

* RunDir: for interacting with the sequencing data output from an
  Illumina sequencing instrument (e.g. NovaSeq 6000)
* FastqDir: for interacting the Fastq data output from Illumina
  BCL-to-Fastq conversion software (e.g. bcl2fastq)

Additional supporting classes for the 'RunDir' class are:

* RunInfo: extract data from the RunInfo.xml file in a run
* RunParameters: extract data from the RunParameters.xml file

Additional supporting classes for the 'FastqDir' class are:

* FastqDirProject: data about a "project" within the Fastq data
* FastqDirSample: data about a "sample" within the Fastq data

Typically only the 'RunDir' and 'FastqDir' classes are explicitly
instantiated; instances of the supporting are created implicitly
within the "top-level" classes. used within them to manage

The 'RunDir' class can be used to fetch information about
a run such as lanes, numbers of cycles and basecall file
format.

The 'FastqDir' class can be used to examine projects, samples
and Fastq files generated by the BCL-to-Fastq conversion.

In addition there are a number of utility functions:

* verify_against_sample_sheet: checks BCL-to-Fastq outputs
  against sample sheet file
* list_missing_fastqs: list missing predicted Fastqs
* summarise_projects: summarise projects in BCL-to-Fastq output
* describe_project: summaries samples in BCL-to-Fastq output
"""

#######################################################################
# Imports
#######################################################################

import os
import logging
import xml.dom.minidom
from functools import reduce
from ... import utils
from .samplesheet import SampleSheet
from .samplesheet import SampleSheetPredictor
from .utils import IlluminaFastq
from .utils import identify_platform
from .exceptions import IlluminaError
from .. import RUN_COMPLETION_FILES

# Module specific logger
logger = logging.getLogger(__name__)

#######################################################################
# Classes
#######################################################################


class RunDir:
    """
    Class for handling Illumina run directory.

    Provides the following properties:

    - path: path to the top-level data directory
    - basecalls_dir: name and full path to the subdirectory holding bcl files
    - sample_sheet_csv: full path of the SampleSheet.csv file
    - runinfo_xml: full path of the RunInfo.xml file
    - runparameters_xml: full path of the RunParameters.xml file
    - bcl_extension: file extension for bcl files (either "bcl" or "bcl.gz")
    - lanes: list of (integer) lane numbers in the run
    - sample_sheet: SampleSheet instance (if the run has an associated
      sample sheet file)
    - runinfo: RunInfo instance (if the run has an associated
      RunInfo.xml file)
    - runparameters: RunParameters instance (if the run has an
      associated RunParameters.xml file)
    - platform: platform name

    Arguments:
      run_dir (str): path to the top-level directory holding
        the raw data from the sequencer
    """

    def __init__(self, run_dir):
        # Top-level directory
        self.path = os.path.abspath(run_dir)
        if not os.path.isdir(self.path):
            raise IlluminaError(f"{self.path}: directory not found "
                                f"(or not a directory?")
        # Basecalls subdirectory
        self.basecalls_dir = os.path.join(self.path,
                                          "Data",
                                          "Intensities",
                                          "BaseCalls")
        # Locate sample sheet
        if os.path.isdir(self.basecalls_dir):
            self.sample_sheet_csv = os.path.join(self.basecalls_dir,
                                                 "SampleSheet.csv")
            if not os.path.isfile(self.sample_sheet_csv):
                self.sample_sheet_csv = None
        else:
            self.sample_sheet_csv = None
            self.basecalls_dir = None
        # Add SampleSheet instance
        if self.sample_sheet_csv:
            self.sample_sheet = SampleSheet(self.sample_sheet_csv)
        else:
            self.sample_sheet = None
        # RunInfo.xml
        self.runinfo_xml = os.path.join(self.path, "RunInfo.xml")
        if not os.path.isfile(self.runinfo_xml):
            self.runinfo_xml = None
        if self.runinfo_xml:
            self.runinfo = RunInfo(self.runinfo_xml)
        else:
            self.runinfo = None
        # RunParameters.xml
        self.runparameters_xml = os.path.join(self.path,
                                              "RunParameters.xml")
        if not os.path.isfile(self.runparameters_xml):
            self.runparameters_xml = None
        if self.runparameters_xml:
            self.runparameters = RunParameters(
                self.runparameters_xml)
        else:
            self.runparameters = None
        # Platform
        if self.runinfo is not None:
            try:
                self.platform = identify_platform(self.runinfo.run_id)
            except IlluminaPlatformError:
                self.platform = "unknown"
        else:
            self.platform = identify_platform(self.path)

    @property
    def bcl_extension(self):
        """
        Get extension of bcl files

        Returns one of 'bcl', 'bcl.gz', 'bcl.bgzf'

        Raises an exception if no matching files are found.
        """
        # Check that the basecalls directory exists
        if self.basecalls_dir is None or \
           not os.path.isdir(self.basecalls_dir):
            raise IlluminaError(
                "Unable to determine bcl extension (no basecalls dir)")
        # Locate the directory for the first cycle in the first lane
        # (HiSeq and MiSeq)
        lane1_cycle1 = os.path.join(self.basecalls_dir, "L001", "C1.1")
        if os.path.isdir(lane1_cycle1):
            for f in os.listdir(lane1_cycle1):
                for ext in (".bcl", ".bcl.gz",):
                    if str(f).endswith(ext):
                        return ext
        # Look in the directory for the first lane (NextSeq)
        lane1 = os.path.join(self.basecalls_dir, "L001")
        for f in os.listdir(lane1):
            for ext in (".bcl.bgzf",):
                if str(f).endswith(ext):
                    return ext
        # Failed to match any known extension, raise exception
        raise IlluminaError("Unable to determine bcl extension")

    @property
    def lanes(self):
        """
        Return list of lane numbers

        Returns a list of integer lane numbers found in the
        run directory
        """
        if self.basecalls_dir is None or \
           not os.path.isdir(self.basecalls_dir):
            return []
        lanes = []
        for d in os.listdir(self.basecalls_dir):
            if d.startswith("L"):
                lanes.append(int(d[1:]))
        return sorted(lanes)

    @property
    def cycles(self):
        """
        Return the number of cycles
        """
        lanes = self.lanes
        if not lanes:
            # No lanes found, cannot count the cycles
            return None
        # Look in first lane
        lane1 = os.path.join(self.basecalls_dir,
                             "L%03d" % lanes[0])
        ncycles = 0
        # Try C1.1 etc directories (MISeq/HISeq)
        for d in os.listdir(lane1):
            if d.startswith("C"):
                cycle = int(d[1:].split(".")[0])
                ncycles = max(ncycles, cycle)
        # If no cycles counted, try .bcl.bgzf files
        # (NextSeq)
        if ncycles == 0:
            for f in os.listdir(lane1):
                if str(f).endswith(".bcl.bgzf"):
                    cycle = int(f.split(".")[0])
                    ncycles = max(ncycles, cycle)
        if ncycles == 0:
            return None
        return ncycles


class RunInfo:
    """
    Class for examining Illumina RunInfo.xml file

    Extracts basic information from a RunInfo.xml file:

    - run_id: the run id e.g.'130805_PJ600412T_0012_ABCDEZXDYY'
    - run_number: the run number e.g. '0012'
    - instrument: the instrument name e.g. 'PJ600412T'
    - date: the run date e.g. '130805'
    - flowcell: the flowcell id e.g. 'ABCDEZXDYY'
    - lane_count: the flowcell lane count e.g. 8
    - bases_mask: bases mask string derived from the read
      information e.g. 'y101,I6,y101'
    - reads: a list of Python dictionaries (one per read)

    Each dictionary in the 'reads' list has the following keys:

    - number: the read number (1,2,3,...)
    - num_cycles: the number of cycles in the read e.g. 101
    - is_indexed_read: whether the read is an index (i.e.
      barcode); either 'Y' or 'N'

    Arguments:
      runinfo_xml (str): path to the RunInfo.xml file
    """

    def __init__(self, runinfo_xml):
        self.runinfo_xml = runinfo_xml
        self.run_id = None
        self.run_number = None
        self.instrument = None
        self.flowcell = None
        self.date = None
        self.lane_count = None
        self.reads = []
        # Process contents
        doc = xml.dom.minidom.parse(self.runinfo_xml)
        run_tag = doc.getElementsByTagName("Run")[0]
        self.run_id = run_tag.getAttribute("Id")
        self.run_number = run_tag.getAttribute("Number")
        self.instrument = \
                doc.getElementsByTagName("Instrument")[0].firstChild.nodeValue
        self.flowcell = \
                doc.getElementsByTagName("Flowcell")[0].firstChild.nodeValue
        self.date = doc.getElementsByTagName('Date')[0].firstChild.nodeValue
        flowcell_layout_tag = doc.getElementsByTagName("FlowcellLayout")[0]
        self.lane_count = flowcell_layout_tag.getAttribute("LaneCount")
        read_tags = doc.getElementsByTagName("Read")
        for read_tag in read_tags:
            self.reads.append({
                "number": read_tag.getAttribute("Number"),
                "num_cycles": read_tag.getAttribute("NumCycles"),
                "is_indexed_read": read_tag.getAttribute("IsIndexedRead")})

    @property
    def bases_mask(self):
        """
        Generate bases mask string from read information

        Returns a bases mask string of the form e.g. 'y68,I6' for input
        into bclToFastq, based on the read information.
        """
        bases_mask = []
        for read in self.reads:
            num_cycles = int(read["num_cycles"])
            if read["is_indexed_read"] == "N":
                bases_mask.append(f"y{num_cycles}")
            elif read["is_indexed_read"] == 'Y':
                bases_mask.append(f"I{num_cycles}")
            else:
                raise IlluminaError(f"'{read['is_indexed_read']}': "
                                    "unrecognised value for "
                                    "'is_indexed_read'")
        return ",".join(bases_mask)


class RunParameters:
    """
    Class for examining Illumina RunParameters.xml file

    Extracts basic information from a RunParameters.xml file:

    - flowcell_mode: the flowcell mode e.g. 'SP','S4'

    Arguments:
      runparameters_xml (str): path to the RunParameters.xml
        file
    """
    def __init__(self, runparameters_xml):
        self.runparameters_xml = runparameters_xml
        self.flowcell_mode = None
        # Process contents
        doc = xml.dom.minidom.parse(self.runparameters_xml)
        run_params = doc.getElementsByTagName("RunParameters")[0]
        try:
            self.flowcell_mode = run_params.\
                                 getElementsByTagName("FlowCellMode")[0].\
                                 firstChild.nodeValue
        except IndexError:
            # Element not found
            self.flowcell_mode = None


class FastqDir:
    """
    Handle directory with Fastqs from bcl-to-fastq conversion

    Provides the following attributes:

    - path: path to the top-level directory generated by the
      bcl-to-fastq conversion
    - projects: list of FastqDirProject objects (one for each
      project defined at the fastq creation stage)
    - undetermined: Project object for the undetermined reads
    - paired_end: True if at least one project is paired end,
      False otherwise
    - format: Format of the directory structure layout (either
      'casava' or 'bcl2fastq2', or None if the format cannot
      be determined)
    - lanes: List of lane numbers present; if there are no lanes
      then this will be a list with 'None' as the only value

    Provides the following methods:

    - get_project(): lookup and return an Project object
      corresponding to the supplied project name

    Arguments:
      illumina_analysis_dir: path to the analysis directory holding
        the fastq files (expected to be in a subdirectory called
        'Unaligned').
      unaligned_dir: (optional) alternative name for the subdirectory
        under illumina_analysis_dir holding the fastq files
    """
    def __init__(self, fastq_dir):
        self.path = os.path.abspath(fastq_dir)
        self.projects = []
        self.undetermined = None
        self.paired_end = False
        self.lanes = []
        self.format = None
        # Check directory exists
        if not os.path.exists(self.path):
            raise IlluminaError(f"'{self.path}': missing Fastqs "
                                "directory")
        # Raise an exception if no projects found
        try:
            self._populate_casava_style()
        except IlluminaError:
            try:
                self._populate_bcl2fastq2_style()
            except Exception as ex:
                raise IlluminaError(f"'{self.path}': exception "
                                    f"attempting to read bcl2fastq2-style "
                                    f"data: {ex}")
        if not self.projects and self.format != 'bcl2fastq2':
            raise IlluminaError(f"'{self.path}': no projects found")
        # Sort projects on name
        self.projects = sorted(self.projects,
                               key=lambda p: p.name)
        # Determine whether data is paired end
        for p in self.projects:
            self.paired_end = (self.paired_end or p.paired_end)
        # Get list of lanes
        for p in self.projects:
            for s in p.samples:
                for fq in s.fastq:
                    lane = IlluminaFastq(fq).lane_number
                    if lane not in self.lanes:
                        self.lanes.append(lane)
        # Interrogate undetermined (in case there were no projects)
        if self.undetermined:
            self.paired_end = self.undetermined.paired_end
            for s in self.undetermined.samples:
                for fq in s.fastq:
                    lane = IlluminaFastq(fq).lane_number
                    if lane not in self.lanes:
                        self.lanes.append(lane)
        self.lanes = sorted([l for l in self.lanes
                             if l is not None or len(self.lanes) == 1])

    def _populate_casava_style(self):
        """
        Find projects for a CASAVA-style directory structure
        """
        # Look for projects
        for f in os.listdir(self.path):
            dirn = os.path.join(self.path,f)
            if f.startswith("Project_") and os.path.isdir(dirn):
                logging.debug("Project dirn: %s" % f)
                self.projects.append(FastqDirProject(dirn))
            elif f == "Undetermined_indices":
                logging.debug("Undetermined dirn: %s" %f)
                self.undetermined = FastqDirProject(dirn)
        # Raise an exception if no projects found
        if not self.projects :
            raise IlluminaError(f"'{self.path}': no CASAVA-style "
                                "projects found")
        else:
            self.format = 'casava'

    def _populate_bcl2fastq2_style(self):
        """
        Find projects for a bcl2fastq2-style directory structure

        The output from bcl2fastq2 can be "flat" (i.e. fastqs
        directly under project dirs) or it can contain "sample"
        subdirs within project dirs, or a mixture of both.

        Generally we expect to find a number of 'undetermined'
        fastqs at the top level of the output (unaligned) directory,
        and the fastq names will contain the 'S1' sample number
        construct.
        """
        # Look for undetermined fastqs
        undetermined_fqs = [f for f in os.listdir(self.path)
                            if (f.startswith("Undetermined_S0_") and
                                f.endswith(".fastq.gz"))]
        if not undetermined_fqs:
            logging.debug("%s: no bcl2fastq2 undetermined fastqs found" %
                          self.path)
        # Look for 'Stats' and 'Reports' subdirs
        got_stats = os.path.isdir(os.path.join(self.path, "Stats"))
        got_reports = os.path.isdir(os.path.join(self.path,
                                                 "Reports"))
        # Look for potential projects
        project_dirs = []
        for d in os.listdir(self.path):
            dirn = os.path.join(self.path, d)
            if not os.path.isdir(dirn):
                continue
            # Get a list of fastq files
            fqs = [f for f in os.listdir(dirn)
                   if (f.endswith(".fastq.gz") and
                       IlluminaFastq(f).sample_number is not None)]
            if fqs:
                # Looks like a project
                project_dirs.append(dirn)
            else:
                # Look in subdirs
                subdirs = [d for d in os.listdir(dirn)
                           if os.path.isdir(os.path.join(dirn, d))]
                if subdirs:
                    for sd in subdirs:
                        fqs = [f for f in os.listdir(os.path.join(dirn, sd))
                               if (f.endswith(".fastq.gz") and
                                   IlluminaFastq(f).sample_number
                                   is not None)] 
                        if fqs:
                            # Looks like a project
                            project_dirs.append(dirn)
                            break; continue
        if not project_dirs:
            logging.debug(f"'{self.path}': no bcl2fastq2-style "
                          "projects found")
        # Raise an exception if no bcl2fastq2-style undetermined or
        # projects found
        if (not undetermined_fqs and not project_dirs) or \
           (not got_stats and not got_reports):
            raise IlluminaError(f"'{self.path}': not a "
                                "bcl2fastq2-style output "
                                "directory")
        # Create project objects
        if undetermined_fqs:
            self.undetermined = FastqDirProject(self.path)
        for dirn in project_dirs:
            self.projects.append(FastqDirProject(dirn))
        self.format = "bcl2fastq2"

    def get_project(self, name):
        """
        Return project that matches 'name'

        Arguments:
          name: name of a project

        Returns:
          Project: matching project object.

        Raises:
          IlluminaError: if no match is found.
        """
        for project in self.projects:
            if project.name == name: return project
        raise IlluminaError(f"'{self.path}': no matching project for "
                            f"'{name}'")


class FastqDirProject:
    """
    Class for storing information on a 'project' within a Fastq directory

    A project is a subset of Fastq files from a run of an Illumina
    sequencer; in the first instance projects are defined within the
    SampleSheet.csv file which is output by the sequencer.

    Note that the "undetermined" fastqs (which hold reads for each lane
    which couldn't be assigned to a barcode during demultiplexing) is also
    considered as a project, and can be processed using an Project
    object.

    Provides the following attributes:

    - name: name of the project
    - dirn: (full) path of the directory for the project
    - expt_type: the application type for the project e.g. RNA-seq,
      ChIP-seq (initially set to None; should be explicitly set by
      the calling subprogram)
    - samples: list of FastqDirSample objects for each sample within
      the project
    - paired_end: True if all samples are paired end, False otherwise
    - undetermined: True if 'samples' are actually undetermined reads

    Arguments:
      project_dir (str): path to the directory holding the samples
        within the project
    """
    def __init__(self, project_dir):
        self.dirn = project_dir
        self.expt_type = None
        self.samples = []
        self.paired_end = True
        self.undetermined = False
        # Test if this looks like a CASAVA/bcl2fastq v1.8 output
        self.project_prefix = "Project_"
        dirname = os.path.basename(self.dirn)
        if dirname.startswith(self.project_prefix) or \
           dirname == "Undetermined_indices":
            # CASAVA/bcl2fastq v1.8
            if dirname == "Undetermined_indices":
                # "Undetermined_indices" from CASAVA/bcl2fastq v1.8
                self.project_prefix = ""
                self.undetermined = True
                self.name = dirname
            else:
                # Standard project, strip prefix
                self.name = dirname[len(self.project_prefix):]
            logging.debug("CASAVA/bcl2fastq 1.8 project: %s" % self.name)
            # Look for samples
            self.sample_prefix = "Sample_"
            for f in os.listdir(self.dirn):
                sample_dirn = os.path.join(self.dirn,f)
                if f.startswith(self.sample_prefix) and \
                   os.path.isdir(sample_dirn):
                    self.samples.append(FastqDirSample(sample_dirn))
        else:
            # Examine fastq files in top-level dir to see if naming scheme
            # follows bcl2fastq v2 convention
            fastqs = [f for f in os.listdir(self.dirn)
                      if (f.endswith(".fastq.gz") and
                          IlluminaFastq(f).sample_number is not None)]
            if fastqs:
                # Check if this is the top level bcl2fastq v2 output
                # i.e. does it contain undetermined reads
                if reduce(lambda x,y: x and
                          os.path.basename(y).startswith("Undetermined_S"),
                          fastqs,True):
                    # These are undetermined fastqs
                    self.undetermined = True
            if not self.undetermined:
                # Even if we already have fastqs, we need to check
                # subdirs for more bcl2fastq v2 style fastqs
                subdirs = [d for d in os.listdir(self.dirn)
                           if os.path.isdir(os.path.join(self.dirn,d))]
                for subdir in subdirs:
                    items = [os.path.join(subdir,x)
                             for x in
                             os.listdir(os.path.join(self.dirn,subdir))]
                    fastqs.extend([f for f in items
                                   if (f.endswith(".fastq.gz") and
                                       IlluminaFastq(f).sample_number
                                       is not None)])
            if not fastqs:
                raise IlluminaError(f"'{self.dirn}': not a project "
                                    f"directory")
            # bcl2fastq v2 doesn't prefix project or sample dir names
            self.project_prefix = ""
            self.sample_prefix = ""
            # Determine project name
            if not self.undetermined:
                self.name = os.path.basename(self.dirn)
            else:
                self.name = "Undetermined_indices"
            logging.debug("bcl2fastq 2 project: %s" % self.name)
            # Determine samples from fastq paths/names
            sample_names = []
            for fq in fastqs:
                if not self.undetermined:
                    try:
                        sample_name,_ = fq.split(os.sep)
                    except ValueError:
                        sample_name = IlluminaFastq(fq).sample_name
                else:
                    # Use laneX as sample name for undetermined
                    try:
                        sample_name = "lane%d" % IlluminaFastq(fq).lane_number
                    except TypeError:
                        # No lane, use undetermined as sample name
                        sample_name = "undetermined"
                if sample_name not in sample_names:
                    sample_names.append(sample_name)
            # Create sample objects and populate with appropriate fastqs
            for sample_name in sample_names:
                sample_dirn = self.dirn
                if not self.undetermined:
                    # Assume no subdir
                    fqs = [f for f in fastqs
                           if IlluminaFastq(f).sample_name == sample_name]
                    if not fqs:
                        # Look for fastqs within a subdir
                        sample_dirn = os.path.join(self.dirn,sample_name)
                        fqs = [f for f in fastqs
                               if f.startswith(f"{sample_name}/")]
                    else:
                        # Do fastqs have a leading subdir?
                        leading_dir = list(set([os.path.dirname(fq)
                                                for fq in fqs]))
                        if len(leading_dir) == 1:
                            # Same leading subdir for all fastqs
                            # Update the sample dir
                            sample_dirn = os.path.join(self.dirn,
                                                       leading_dir[0])
                else:
                    # Handle 'undetermined' data
                    # Try Fastqs with matching lane
                    fqs = [fq for fq in fastqs
                           if IlluminaFastq(fq).lane_number is not None and
                           "lane%d" % IlluminaFastq(fq).lane_number
                           == sample_name]
                    if not fqs:
                        # No lane, take all fastqs without a lane
                        fqs = [fq for fq in fastqs
                               if IlluminaFastq(fq).lane_number is None]
                self.samples.append(FastqDirSample(sample_dirn,
                                                   fastqs=fqs,
                                                   name=sample_name,
                                                   prefix=""))
        # Raise an exception if no samples found
        if not self.samples:
            raise IlluminaError(f"'{self.name}': no samples found for "
                                f"project")
        # Sort samples on name
        self.samples = sorted(self.samples, key=lambda s: s.name)
        # Determine whether project is paired end
        for s in self.samples:
            self.paired_end = (self.paired_end and s.paired_end)

    @property
    def full_name(self):
        """
        Return full name for project

        The full name is "<name>_<expt_type>" (e.g. "PJB_miRNA"), but
        reverts to just "<name>" if no experiment type is set (e.g. "PJB").

        The full name is typically used as the name of the analysis
        subdirectory for the project in the analysis pipeline.
        """
        if self.expt_type is not None:
            return f"{self.name}_{self.expt_type}"
        else:
            return self.name

    def pretty_print_samples(self):
        """
        Return a nicely formatted string describing the sample names

        Wraps a call to 'pretty_print_names' function.
        """
        return utils.pretty_print_names(self.samples)


class FastqDirSample:
    """
    Class for storing information on a 'sample' within a Fastq directory

    A sample is a fastq file generated within an Illumina sequencer run.

    Provides the following attributes:

    - name: sample name
    - dirn: (full) path of the directory for the sample
    - fastq: name of the fastq.gz file (without leading directory,
      join to 'dirn' to get full path)
    - paired_end: boolean; indicates whether sample is paired end

    Arguments:
      sample_dir (str): path to the directory holding the fastq.gz
        files for the sample
      fastqs (list): optional, a list of Fastq files associated with
        the sample (expected to be under the directory 'dirn')
      name (str): optional, the name of the sample (if not supplied
        then will attempt to determine automatically)
      prefix (str): optional, explicitly specify the 'prefix' placed
        in front of the sample name to generate the matching
        directory
    """
    def __init__(self, sample_dir, fastqs=None, name=None,
                 prefix="Sample_"):
        self.dirn = sample_dir
        self.fastq = []
        self.paired_end = False
        # Deal with fastq files
        if fastqs is None:
            fastqs = [f for f in os.listdir(self.dirn)
                      if f.endswith(".fastq.gz")]
        else:
            fastqs = [os.path.basename(f) for f in fastqs]
        self.sample_prefix = prefix
        # Set sample name
        if name is not None:
            # Supplied explicitly
            self.name = name
        elif self.sample_prefix and \
           os.path.basename(self.dirn).startswith(self.sample_prefix):
            # Determine from prefixed directory name
            self.name = os.path.basename(self.dirn)[len(self.sample_prefix):]
        else:
            # No prefix, obtain name from fastqs
            self.sample_prefix = ""
            self.name = IlluminaFastq(fastqs[0]).sample_name
            # Special case: undetermined 'sample' is 'laneX'
            if self.name == 'Undetermined':
                try:
                    self.name = "lane%d" % IlluminaFastq(fastqs[0]).lane_number
                except TypeError:
                    # No lane number
                    self.name = "undetermined"
        logging.debug("\tSample: %s" % self.name)
        # Add fastq files
        for f in fastqs:
            self.add_fastq(f)
            logging.debug("\tFastq : %s" % f)
        if not self.fastq:
            logging.debug("\tUnable to find fastq.gz files for %s" %
                          self.name)

    def add_fastq(self, fastq):
        """
        Add a reference to a fastq file in the sample

        Arguments:
          fastq (str): name of the fastq file
        """
        self.fastq.append(fastq)
        # Sort fastq's into order
        self.fastq = sorted(self.fastq)
        # Check paired-end status
        if not self.paired_end:
            fq = IlluminaFastq(fastq)
            if fq.read_number == 2:
                self.paired_end = True

    def fastq_subset(self, read_number=None, full_path=False):
        """
        Return a subset of fastq files from the sample

        Arguments:
          read_number (int): select subset based on read_number
            (1 or 2)
          full_path (bool): if True then fastq files will be
            returned with the full path; if False (default) then
            as file names only.

        Returns:
          List: Fastq files matching the selection criteria.
        """
        # Build list of fastqs that match the selection criteria
        fastqs = []
        for fastq in self.fastq:
            fq = IlluminaFastq(fastq)
            if fq.read_number is None:
                raise IlluminaError("Unable to determine read number "
                                    "for %s" % fastq)
            if fq.read_number == read_number:
                if full_path:
                    fastqs.append(os.path.join(self.dirn,fastq))
                else:
                    fastqs.append(fastq)
        # Sort into dictionary order and return
        return sorted(fastqs)

    def __repr__(self):
        """
        Implement __repr__ built-in

        Return string representation for the Sample (i.e. the
        sample name.
        """
        return str(self.name)


#######################################################################
# Functions
#######################################################################


def verify_against_sample_sheet(fastq_dir, sample_sheet,
                                include_sample_dir=False):
    """
    Checks existence of predicted outputs from a sample sheet

    Arguments:
      fastq_dir (FastqDir): FastqDir instance to verify
      sample_sheet (str): path to sample sheet file
      include_sample_dir (bool): if True then include a
        'sample_name' directory level when checking for
        bcl2fastq2 outputs

    Returns:
      True if all the predicted outputs from the sample sheet are
        found, False otherwise.
    """
    return not bool(list_missing_fastqs(
        fastq_dir,
        sample_sheet,
        include_sample_dir=include_sample_dir))


def list_missing_fastqs(fastq_dir, sample_sheet,
                        include_sample_dir=False):
    """
    Lists missing Fastq files predicted from sample sheet

    Arguments:
      fastq_dir (FastqDir): FastqDir instance to check
      sample_sheet (str): path to a sample sheet file
      include_sample_dir (bool): if True then include
        a 'sample_name' directory level when checking
        for bcl2fastq2 outputs

    Returns:
      List: list of paths of missing Fastq files, relative
        to the unaligned directory. List is empty if there
        are no missing files.
    """
    # Initialise
    missing_fastqs = []
    # Gather information
    sample_sheet = SampleSheet(sample_sheet)
    if sample_sheet.has_lanes:
        lanes = None
    else:
        lanes = fastq_dir.lanes
    no_lane_splitting = ((len(fastq_dir.lanes) == 1) and
                         (fastq_dir.lanes[0] is None))
    # Set up predictor instance
    predictor = SampleSheetPredictor(sample_sheet=sample_sheet)
    predictor.set(package=fastq_dir.format,
                  paired_end=fastq_dir.paired_end,
                  lanes=lanes,
                  no_lane_splitting=no_lane_splitting,
                  force_sample_dir=include_sample_dir)
    # Loop over predictions and check corresponding outputs exist
    verified = True
    for proj in predictor.project_names:
        project = predictor.get_project(proj)
        for smpl in project.sample_ids:
            sample = project.get_sample(smpl)
            path = os.path.join(fastq_dir.path,
                                project.dir_name)
            if sample.dir_name:
                path = os.path.join(path,sample.dir_name)
            for fq in sample.fastqs():
                fastq = os.path.join(path, fq)
                if not os.path.exists(fastq):
                    missing_fastqs.append(
                        os.path.relpath(fastq, fastq_dir.path))
    # Return list of missing files
    return missing_fastqs


def summarise_projects(fastq_dir):
    """
    Short summary of projects, suitable for logging file

    The summary description is a one line summary of the project names
    along with the number of samples in each, and an indication if the
    run was paired-ended.

    Arguments:
      fastq_dir (FastqDir): FastqDir instance to summarise

    Returns:
      String: summary descriptions.
    """
    summary = ""
    project_summaries = []
    if fastq_dir.paired_end:
        summary = "Paired end: "
    for project in fastq_dir.projects:
        n_samples = len(project.samples)
        project_summaries.append(f"{project.name} "
                                 f"({n_samples} "
                                 f"sample{'s' if n_samples != 1 else ''})")
    summary += "; ".join(project_summaries)
    return summary


def describe_project(project):
    """
    Generate description string for samples in a project

    Description string gives the project name and a human-readable
    summary of the sample names, plus number of samples and whether
    the data is paired end.

    Example output: "Project Control: PhiX_1-2  (2 samples)"

    Arguments
      project (Project): Project instance

    Returns
      String: description of the project.
    """
    # Gather information
    paired_end = project.paired_end
    n_samples = len(project.samples)
    multiple_fastqs_per_sample = False
    for s in project.samples:
        n_fastqs = len(s.fastq)
        if (paired_end and n_fastqs > 2) or \
           (not paired_end and n_fastqs > 1):
            multiple_fastqs_per_sample = True
            break
    # Build description
    description = f"{project.name}: {project.pretty_print_samples()}"
    sample_names = project.pretty_print_samples()
    description += f" ({n_samples} "
    if paired_end:
        description += "paired end "
    if n_samples == 1:
        description += "sample"
    else:
        description += "samples"
    if multiple_fastqs_per_sample:
        description += ", multiple fastqs per sample"
    description += ")"
    return str(description)
